src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('top.urls')),
    path(r'question/', include('question.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

src/question/urls.py
from django.urls import path
from question.views import CategoryDetailView

app_name = 'question'
urlpatterns = [
    path('category/<int:pk>/',
         CategoryDetailView.as_view(), name='category_detail'),
]

src/top/urls.py
from django.urls import path
from top.views import Index, Guide

urlpatterns = [
    path('', Index.as_view(), name='top'),
    path('guide/', Guide.as_view(), name='guide'),
]

src/question/models.py
# -*- coding:utf-8 -*-
from django.db import models
import os
import storages.backends.s3boto3
from django.conf import settings
from django.core.files.storage import FileSystemStorage

# アップロードストレージ定義(環境変数で定義)
if os.environ['UPLOAD_STORAGE'] == 'S3':
    # S3プライベート設定(有効期限は1ヶ月)
    protected_storage = storages.backends.s3boto3.S3Boto3Storage(
        acl='private',
        querystring_auth=True,
        querystring_expire=2678400)
else:
    # ローカルストレージ利用時
    protected_storage = FileSystemStorage(location=settings.MEDIA_ROOT)


class Category(models.Model):
    """Category Class"""
    name = models.CharField(max_length=50, blank=False,
                            null=False, verbose_name=u'カテゴリ')
    image = models.ImageField(upload_to='category/image/%Y%m%d', db_index=True,
                              blank=False, verbose_name=u'カテゴリイメージ',
                              null=False, storage=protected_storage)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = u'カテゴリ'
        verbose_name_plural = u'カテゴリ'


class Question(models.Model):
    """Question Class"""
    text = models.TextField(max_length=255, blank=False,
                            null=False, verbose_name=u'本文')
    category = models.ManyToManyField(
        Category, verbose_name=u'カテゴリ', blank=False)

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = u'質問'
        verbose_name_plural = u'質問'

src/question/views.py
# -*- coding:utf-8 -*-
from django.views.generic import DetailView
from django.views.decorators.cache import never_cache
from django.contrib import messages
from django.shortcuts import redirect
from django.utils.decorators import method_decorator
from question.models import Question, Category


class CategoryDetailView(DetailView):
    """Category Detail View Class"""
    template_name = 'question/detail.html'
    model = Category
    redirect_msg = 'カテゴリが見つかりませんでした。'

    @method_decorator(never_cache)
    def dispatch(self, *args, **kwargs):
        # Check whether the question exists
        try:
            Category.objects.get(pk=kwargs['pk'])
            return super(CategoryDetailView, self).dispatch(*args, **kwargs)
        except Category.DoesNotExist:
            messages.warning(self.request, self.redirect_msg)
            return redirect('/')

    def get_context_data(self, **kwargs):
        # Get ONE question from all questions related to the category
        context = super(CategoryDetailView, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all().order_by('id')
        context['question'] = Question.objects.filter(
            category=kwargs['object']).order_by('?')[:10].first
        return context

src/top/views.py
# -*- coding:utf-8 -*-
from django.views.generic import View
from django.template.response import TemplateResponse
from django.views.decorators.cache import never_cache
from django.utils.decorators import method_decorator
from question.models import Category


class Index(View):
    """ Top Page """
    http_method_names = ["get"]
    template = "top/index.html"

    # Disable cache decorator
    @method_decorator(never_cache)
    def dispatch(self, *args, **kwargs):
        return super(Index, self).dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        # Get categories
        categories = Category.objects.all().order_by('id')
        context = {'categories': categories}
        return TemplateResponse(request, self.template, context)


class Guide(View):
    """ Guide Page """
    http_method_names = ["get"]
    template = "top/guide.html"

    # Disable cache decorator
    @method_decorator(never_cache)
    def dispatch(self, *args, **kwargs):
        return super(Guide, self).dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        # Get categories
        categories = Category.objects.all().order_by('id')
        context = {'categories': categories}
        return TemplateResponse(request, self.template, context)

templates/_footer.html
<div id="footer" class="bg-dark fixed-bottom">
  <div class="container">
    <p class="text-white credit">&copy; 2020 <strong> Reflessione </strong></p>
  </div>
</div>

templates/_nav.html
{% load staticfiles %}
<div id="header" class="bg-dark sticky-top">
  <div class="container">
    <nav class="nav navbar-expand-lg d-flex justify-content-between align-items-center">
      <div class="nav-item">
        <a class="h2 nav-link text-white" href="/">
          <i class="fas fa-rocket"></i> Reflessione
        </a>
      </div>
      <ul class="navbar-nav ">
        <li class="nav-item">
          <a class="nav-link text-white" href="/"><i class="fas fa-home"></i> HOME</a>
        </li>
        {% if categories %}
          <li class="nav-item ">
            <a class="nav-link dropdown-toggle text-white" href="/" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-tags"></i> CATEGORIES
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for category in categories %}
                <a class="dropdown-item" href="{% url 'question:category_detail' category.id %}">{{category.name}}</a>
              {% endfor %}
            </div>
          </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link text-white" href="/guide"><i class="fas fa-question-circle"></i> GUIDE</a>
        </li>
      </ul>
    </nav>
  </div>
</div>

templates/base.html
<!DOCTYPE html>
<html lang="ja" ng-app>

<head>
  <meta charset="utf-8">
  {% load staticfiles %}
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Riflessione">

  <title>{% block title %}Riflessione - One on One Question Generator{% endblock %}</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static "css/all.css" %}">

  <!-- javascript -->
  {# <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script> #}
  <script type="text/javascript" src="{% static "js/jquery-3.5.1.min.js" %}"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  <script type="text/javascript" src="{% static "js/all.js" %}"></script>

  {% block head %}{% endblock %}
</head>


<body>
  <!-- /Wrap -->
  <div id="wrap" class="bg-light" >
    {% block nav %}
    {% include '_nav.html' %}
    {% endblock nav %}

    {% block container %}
    {% block messages %}
    {% endblock messages %}
    {% block errors %}
    {% endblock errors %}
    {% endblock container %}
  </div>
  <!-- /Wrap -->
  <!-- Footer -->
  {% block footer %}
  {% include "_footer.html" %}
  {% endblock footer %}
  <!-- /Footer -->

</body>
</html>

templates/question/detail.html
{% extends "base.html" %}

{% load staticfiles %}

{% block head %}
{% endblock %}

{% block container %}
  <div class="container">
    <ol class="breadcrumb">
        <li><a href="/">HOME</a> / </li>
        <li class="active"><a href="{% url 'question:category_detail' object.id %}">{{ object }}</a></li>
      </ol>
    <div class="row" style="min-height:calc(100vh - 150px)">
      <h2 class="font-italic mx-auto my-auto" style="font-size: 50pt;">
        "{{ question.text }}"
      </h2>
    </div>
  </div>
{% endblock %}

templates/top/guide.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block container %}
<div class="container">
  <div class="row" style="min-height:calc(100vh - 102px)">
    <h2>What is a one on one?</h2>
    <p>1on1 is a one-on-one interview that your boss and subordinates have on a regular basis. Many companies are showing interest because their bosses can expect various effects such as problem solving and human resource development by listening to their subordinates and giving appropriate feedback.</p>

    <h2>Difference from evaluation interview</h2>
    <p>Similar to 1on1, the evaluation interview is known as an “opportunity for the boss and subordinates to talk one-on-one”. However, in 1on1 and evaluation interviews, the purpose of implementation, the method of interaction, and the frequency differ. The evaluation interview aims to determine and notify the personnel evaluation of the subordinates, while 1on1 aims to enhance or withdraw the subordinates' capabilities. Because the purpose is different, the dialogue method is often evaluated in the interview "from the boss to the subordinate", whereas 1on1 has the difference that "the boss and subordinates" talk in many cases. In addition, evaluation interviews are mainly conducted only at the time of personnel evaluation, such as at the end of the period, while 1on1 is performed in a short cycle such as "once a week" and "once every other week" (once a month at the longest). Varies.</p>

    <h3>1. Tell the purpose</h3>
    <p>If you tell only that 1on1 will be implemented, some subordinates may feel uneasy, such as "what kind of story should I talk about?" .. In order to bring out the true intentions of subordinates with 1on1, it is important to tell in advance what purpose 1on1 will be carried out. Let us know that it is "time to get closer to the worries/issues of your subordinates and to lead to growth", and will not directly affect personnel evaluation.</p>

    <h3>2. Decide the date</h3>
    <p>When deciding on a 1on1 date, frequency, day of the week and time of day are important. If you leave too much space, there is a possibility that you will not be able to report or give feedback in real time, or you will forget the previous 1on1 contents. If possible, try once a week, at least once a month.</p>

    <h3>3. Conduct 1on1</h3>
    <p>On the day, it is important to create an atmosphere that is easy to talk, such as chatting at the beginning, in order to relieve the tension of subordinates. Also, since we will spend valuable time on this, during 1on1, make a note of "what did your subordinate talk about?" and "what advice did you give to it?" If you decide the future direction and action to some extent, you can make the next 1on1 meaningful.</p>

    <h3>4. Preparation for the next time</h3>
    <p>After finishing 1on1, we will share the contents of the memo created on the day for review by both parties. If your subordinate informs you of your desire to move or your intention to retire at 1on1, you will also need to inform relevant personnel such as personnel manager. Also, be sure to inform your subordinates of your next 1on1 schedule and theme.</p>
  </div>
</div>
{% endblock container %}

templates/top/index.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block container %}
<div class="container">
  <div class="row">
    <p class="mx-auto my-3">
      Please choose your favorite genre.
    </p>
  </div>
  <div class="row" style="min-height:calc(100vh - 158px)">
    {% for category in categories %}
    <div class="col-sm-6 col-md-3 my-2">
      <div class="card img-thumbnail" style="width: 20rem;">
        <a href="{% url 'question:category_detail' category.id %}">
          <img class="card-img-top" src="{{ category.image.url }}" width="300px" height="200px" style="object-fit: cover;">
        </a>
        <div class="card-body px-2 py-3">
          <a class="text-secondary" href="{% url 'question:category_detail' category.id %}">
            <h6 class="card-title font-weight-bold">{{category.name}}</h6>
          </a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  <hr>
  <script></script>
</div>
{% endblock container %}